### ISSUE TITLE
Can't install through CocoaPods

### ISSUE THREAD

**Issue by LinusGeffarth** [iMhdi/MBDocCapture#1]
Recently discovered this repo and wanted to check it out but was unable to install the `MBDocCapture` using CocoaPods:

>[!] Unable to find a specification for `MBDocCapture`

I tried the following:

- `pod 'MBDocCapture', '>= 0.9'` (from `readme.md`)
- `pod 'MBDocCapture', '>= 0.1.1'` (b/c that's the version in the `.podspec`)
- `pod 'MBDocCapture'`

Neither of those work, unfortunately.

**Comment by iMhdi** [comment]
The name of the pod in your podfile should be enough, I have updated the `readme.md` to fix that version mismatch, just add the following :
- pod 'MBDocCapture'

And try running `pod update` instead of `pod install` to update your local `.cocoapods/repos/master`
