### ISSUE TITLE
View Controller not conforming to protocol, even though all methods are implemented

### ISSUE THREAD

**Issue by LinusGeffarth** [iMhdi/MBDocCapture#2]
As the readme suggests, I made my view controller conform to `ImageScannerControllerDelegate` and added all 4 protocol methods to my code:

    extension DocumentUploaderViewController: ImageScannerControllerDelegate {
        func imageScannerController(_ scanner: ImageScannerController, didFinishScanningWithResults results: ImageScannerResults) {
            scanner.dismiss(animated: true)
        }
        
        func imageScannerController(_ scanner: ImageScannerController, didFinishScanningWithPage1Results page1Results: ImageScannerResults, andPage2Results page2Results: ImageScannerResults) {
            scanner.dismiss(animated: true)
        }
        
        func imageScannerControllerDidCancel(_ scanner: ImageScannerController) {
            scanner.dismiss(animated: true)
        }
        
        func imageScannerController(_ scanner: ImageScannerController, didFailWithError error: Error) {
            scanner.dismiss(animated: true)
        }
    }

Now, Xcode (10.2.1) complains that I'm still missing some protocol stubs:

>Type 'DocumentUploaderViewController' does not conform to protocol 'ImageScannerControllerDelegate'  
>Do you want to add protocol stubs?

When I press `Fix`, Xcode adds the `didFailWithError` method:

    func imageScannerController(_ scanner: ImageScannerController, didFailWithError error: Error) {
    }

...and then complains that I have added an invalid redeclaration of the method (because it was already there!):

>Invalid redeclaration of 'imageScannerController(_:didFailWithError:)'

I have already tried:

- build
- clean derived data
- clean & build
- quit Xcode, clean, build
- reboot my Mac (10.14.3), open Xcode, clean, build

None of these tries helped.  
Any ideas?

**Comment by iMhdi** [comment]
I ran your code, and it worked just fine, maybe the code inside your pod got changed somehow ?

Try running the demo app and let me know.
Also, try removing and installing the pod again.

**Comment by LinusGeffarth** [comment]
Thanks for the quick response. The demo project builds fine. 🤔
I already ran `pod update` and `pod install`, removed the pod and added it back, idk what's wrong.

**Comment by iMhdi** [comment]
I'm afraid this issue has to do with your project and not the with the framework.

I'll gladly help you out with the implementation, if you don't mind sharing your source code. Drop me an email it you're interested.

**Comment by LinusGeffarth** [comment]
Appreciate it, but can't share, unfortunately. Thanks anyway!

**Comment by LinusGeffarth** [comment]
@iMhdi just to let you know, I found the issue: I have an `Error` model in my project so I had to change the method declaration to `didFailWithError error: Swift.Error`. Now it works :)
