### ISSUE TITLE
Landscape support

### ISSUE THREAD

**Issue by LinusGeffarth** [iMhdi/MBDocCapture#3]
I'm developing an iPad app that is landscape-only. Is it possible to present the `ImageScannerController` in landscape?

**Comment by LinusGeffarth** [comment]
@iMhdi umm yes, no, maybe?

**Comment by iMhdi** [comment]
v0.1.3 supports device rotation :)

**Comment by LinusGeffarth** [comment]
@iMhdi I updated to 0.1.3 but it 1) requires my app to support portrait mode and 2) still only shows in portrait.

**Comment by LinusGeffarth** [comment]
@iMhdi I updated to 0.1.3 but it 1) requires my app to support portrait mode and 2) still only shows in portrait. I'm probs just doing sth. wrong...

**Comment by LinusGeffarth** [comment]
@iMhdi any updates on this?
