### ISSUE TITLE
Tab bar buttons missing

### ISSUE THREAD

**Issue by LinusGeffarth** [iMhdi/MBDocCapture#4]
I've followed the readme and implemented the `ImageScannerController` like this:

    let scannerViewController = ImageScannerController(delegate: self)
    present(scannerViewController, animated: true)

Now, when trying it out on my device, it all works fine, but the tab bar buttons are missing:

![IMG_2DB9E9784EB6-1](https://user-images.githubusercontent.com/9455439/57019560-35951d80-6c27-11e9-86e9-c07aefa7dc76.jpeg)

I've noticed, that I can still press the buttons when pressing at the very edge of the screen.  
Have I overlooked any setting or what's wrong here?

**Comment by iMhdi** [comment]
I must've made a mistake in trying to load the icons, I will get to it in the next couple of days, in the meantime I would suggest you copy the icons from the the repository into your project you'll find them in **MBDocCapture/Assets/Icons/**

**Comment by LinusGeffarth** [comment]
Next couple days is totally sufficient, thanks!
While you're at it: I suggest using asset catalogs, and more importantly **pdf icons**, instead of .png files. They are much smaller in terms of file size and scale, so you don't have to use any @2x or @3x image versions.

**Comment by iMhdi** [comment]
Make sure you don't forget to share the download link for your app when it's ready :)
